[build]
    publish = "."
    functions = "netlify/functions"
[functions]
    node_bundler = "esbuild"
[[redirects]]
    force = true
    status = 200
    from = "/*"
    to = "/.netlify/functions/index/:splat"
